/**
 * BundledTools.ts — Auto-generated Static Tool Bundler Map
 * 
 * Generates direct static import bindings for all 97 OS capabilities across 10 priority domains.
 * DO NOT EDIT MANUALLY. Generated by src/tools/loader/build_tools.mjs
 */

export interface RawToolBundle {
  tool: any;
  workflow: any;
  knowledge: any;
  examples: any;
  tests: any;
  folderPath: string;
}

import t_0 from '../../../tools/filesystem/list/tool.json';
import w_0 from '../../../tools/filesystem/list/workflow.json';
import k_0 from '../../../tools/filesystem/list/knowledge.json';
import e_0 from '../../../tools/filesystem/list/examples.json';
import s_0 from '../../../tools/filesystem/list/tests.json';
import t_1 from '../../../tools/filesystem/navigate/tool.json';
import w_1 from '../../../tools/filesystem/navigate/workflow.json';
import k_1 from '../../../tools/filesystem/navigate/knowledge.json';
import e_1 from '../../../tools/filesystem/navigate/examples.json';
import s_1 from '../../../tools/filesystem/navigate/tests.json';
import t_2 from '../../../tools/filesystem/read/tool.json';
import w_2 from '../../../tools/filesystem/read/workflow.json';
import k_2 from '../../../tools/filesystem/read/knowledge.json';
import e_2 from '../../../tools/filesystem/read/examples.json';
import s_2 from '../../../tools/filesystem/read/tests.json';
import t_3 from '../../../tools/filesystem/search/tool.json';
import w_3 from '../../../tools/filesystem/search/workflow.json';
import k_3 from '../../../tools/filesystem/search/knowledge.json';
import e_3 from '../../../tools/filesystem/search/examples.json';
import s_3 from '../../../tools/filesystem/search/tests.json';
import t_4 from '../../../tools/filesystem/copy/tool.json';
import w_4 from '../../../tools/filesystem/copy/workflow.json';
import k_4 from '../../../tools/filesystem/copy/knowledge.json';
import e_4 from '../../../tools/filesystem/copy/examples.json';
import s_4 from '../../../tools/filesystem/copy/tests.json';
import t_5 from '../../../tools/filesystem/locate_files/tool.json';
import w_5 from '../../../tools/filesystem/locate_files/workflow.json';
import k_5 from '../../../tools/filesystem/locate_files/knowledge.json';
import e_5 from '../../../tools/filesystem/locate_files/examples.json';
import s_5 from '../../../tools/filesystem/locate_files/tests.json';
import t_6 from '../../../tools/filesystem/locate_folders/tool.json';
import w_6 from '../../../tools/filesystem/locate_folders/workflow.json';
import k_6 from '../../../tools/filesystem/locate_folders/knowledge.json';
import e_6 from '../../../tools/filesystem/locate_folders/examples.json';
import s_6 from '../../../tools/filesystem/locate_folders/tests.json';
import t_7 from '../../../tools/filesystem/grep/tool.json';
import w_7 from '../../../tools/filesystem/grep/workflow.json';
import k_7 from '../../../tools/filesystem/grep/knowledge.json';
import e_7 from '../../../tools/filesystem/grep/examples.json';
import s_7 from '../../../tools/filesystem/grep/tests.json';
import t_8 from '../../../tools/filesystem/move/tool.json';
import w_8 from '../../../tools/filesystem/move/workflow.json';
import k_8 from '../../../tools/filesystem/move/knowledge.json';
import e_8 from '../../../tools/filesystem/move/examples.json';
import s_8 from '../../../tools/filesystem/move/tests.json';
import t_9 from '../../../tools/filesystem/rename/tool.json';
import w_9 from '../../../tools/filesystem/rename/workflow.json';
import k_9 from '../../../tools/filesystem/rename/knowledge.json';
import e_9 from '../../../tools/filesystem/rename/examples.json';
import s_9 from '../../../tools/filesystem/rename/tests.json';
import t_10 from '../../../tools/filesystem/compress/tool.json';
import w_10 from '../../../tools/filesystem/compress/workflow.json';
import k_10 from '../../../tools/filesystem/compress/knowledge.json';
import e_10 from '../../../tools/filesystem/compress/examples.json';
import s_10 from '../../../tools/filesystem/compress/tests.json';
import t_11 from '../../../tools/filesystem/extract/tool.json';
import w_11 from '../../../tools/filesystem/extract/workflow.json';
import k_11 from '../../../tools/filesystem/extract/knowledge.json';
import e_11 from '../../../tools/filesystem/extract/examples.json';
import s_11 from '../../../tools/filesystem/extract/tests.json';
import t_12 from '../../../tools/filesystem/duplicate/tool.json';
import w_12 from '../../../tools/filesystem/duplicate/workflow.json';
import k_12 from '../../../tools/filesystem/duplicate/knowledge.json';
import e_12 from '../../../tools/filesystem/duplicate/examples.json';
import s_12 from '../../../tools/filesystem/duplicate/tests.json';
import t_13 from '../../../tools/filesystem/delete/tool.json';
import w_13 from '../../../tools/filesystem/delete/workflow.json';
import k_13 from '../../../tools/filesystem/delete/knowledge.json';
import e_13 from '../../../tools/filesystem/delete/examples.json';
import s_13 from '../../../tools/filesystem/delete/tests.json';
import t_14 from '../../../tools/filesystem/trash/tool.json';
import w_14 from '../../../tools/filesystem/trash/workflow.json';
import k_14 from '../../../tools/filesystem/trash/knowledge.json';
import e_14 from '../../../tools/filesystem/trash/examples.json';
import s_14 from '../../../tools/filesystem/trash/tests.json';
import t_15 from '../../../tools/filesystem/restore/tool.json';
import w_15 from '../../../tools/filesystem/restore/workflow.json';
import k_15 from '../../../tools/filesystem/restore/knowledge.json';
import e_15 from '../../../tools/filesystem/restore/examples.json';
import s_15 from '../../../tools/filesystem/restore/tests.json';
import t_16 from '../../../tools/filesystem/permissions/tool.json';
import w_16 from '../../../tools/filesystem/permissions/workflow.json';
import k_16 from '../../../tools/filesystem/permissions/knowledge.json';
import e_16 from '../../../tools/filesystem/permissions/examples.json';
import s_16 from '../../../tools/filesystem/permissions/tests.json';
import t_17 from '../../../tools/filesystem/disk_usage/tool.json';
import w_17 from '../../../tools/filesystem/disk_usage/workflow.json';
import k_17 from '../../../tools/filesystem/disk_usage/knowledge.json';
import e_17 from '../../../tools/filesystem/disk_usage/examples.json';
import s_17 from '../../../tools/filesystem/disk_usage/tests.json';
import t_18 from '../../../tools/filesystem/recent_files/tool.json';
import w_18 from '../../../tools/filesystem/recent_files/workflow.json';
import k_18 from '../../../tools/filesystem/recent_files/knowledge.json';
import e_18 from '../../../tools/filesystem/recent_files/examples.json';
import s_18 from '../../../tools/filesystem/recent_files/tests.json';
import t_19 from '../../../tools/filesystem/mkdir/tool.json';
import w_19 from '../../../tools/filesystem/mkdir/workflow.json';
import k_19 from '../../../tools/filesystem/mkdir/knowledge.json';
import e_19 from '../../../tools/filesystem/mkdir/examples.json';
import s_19 from '../../../tools/filesystem/mkdir/tests.json';
import t_20 from '../../../tools/filesystem/create/tool.json';
import w_20 from '../../../tools/filesystem/create/workflow.json';
import k_20 from '../../../tools/filesystem/create/knowledge.json';
import e_20 from '../../../tools/filesystem/create/examples.json';
import s_20 from '../../../tools/filesystem/create/tests.json';
import t_21 from '../../../tools/application/open/tool.json';
import w_21 from '../../../tools/application/open/workflow.json';
import k_21 from '../../../tools/application/open/knowledge.json';
import e_21 from '../../../tools/application/open/examples.json';
import s_21 from '../../../tools/application/open/tests.json';
import t_22 from '../../../tools/application/close/tool.json';
import w_22 from '../../../tools/application/close/workflow.json';
import k_22 from '../../../tools/application/close/knowledge.json';
import e_22 from '../../../tools/application/close/examples.json';
import s_22 from '../../../tools/application/close/tests.json';
import t_23 from '../../../tools/application/force_quit/tool.json';
import w_23 from '../../../tools/application/force_quit/workflow.json';
import k_23 from '../../../tools/application/force_quit/knowledge.json';
import e_23 from '../../../tools/application/force_quit/examples.json';
import s_23 from '../../../tools/application/force_quit/tests.json';
import t_24 from '../../../tools/application/focus/tool.json';
import w_24 from '../../../tools/application/focus/workflow.json';
import k_24 from '../../../tools/application/focus/knowledge.json';
import e_24 from '../../../tools/application/focus/examples.json';
import s_24 from '../../../tools/application/focus/tests.json';
import t_25 from '../../../tools/application/minimize/tool.json';
import w_25 from '../../../tools/application/minimize/workflow.json';
import k_25 from '../../../tools/application/minimize/knowledge.json';
import e_25 from '../../../tools/application/minimize/examples.json';
import s_25 from '../../../tools/application/minimize/tests.json';
import t_26 from '../../../tools/application/maximize/tool.json';
import w_26 from '../../../tools/application/maximize/workflow.json';
import k_26 from '../../../tools/application/maximize/knowledge.json';
import e_26 from '../../../tools/application/maximize/examples.json';
import s_26 from '../../../tools/application/maximize/tests.json';
import t_27 from '../../../tools/application/list_running/tool.json';
import w_27 from '../../../tools/application/list_running/workflow.json';
import k_27 from '../../../tools/application/list_running/knowledge.json';
import e_27 from '../../../tools/application/list_running/examples.json';
import s_27 from '../../../tools/application/list_running/tests.json';
import t_28 from '../../../tools/application/install/tool.json';
import w_28 from '../../../tools/application/install/workflow.json';
import k_28 from '../../../tools/application/install/knowledge.json';
import e_28 from '../../../tools/application/install/examples.json';
import s_28 from '../../../tools/application/install/tests.json';
import t_29 from '../../../tools/application/uninstall/tool.json';
import w_29 from '../../../tools/application/uninstall/workflow.json';
import k_29 from '../../../tools/application/uninstall/knowledge.json';
import e_29 from '../../../tools/application/uninstall/examples.json';
import s_29 from '../../../tools/application/uninstall/tests.json';
import t_30 from '../../../tools/browser/navigate/tool.json';
import w_30 from '../../../tools/browser/navigate/workflow.json';
import k_30 from '../../../tools/browser/navigate/knowledge.json';
import e_30 from '../../../tools/browser/navigate/examples.json';
import s_30 from '../../../tools/browser/navigate/tests.json';
import t_31 from '../../../tools/browser/search/tool.json';
import w_31 from '../../../tools/browser/search/workflow.json';
import k_31 from '../../../tools/browser/search/knowledge.json';
import e_31 from '../../../tools/browser/search/examples.json';
import s_31 from '../../../tools/browser/search/tests.json';
import t_32 from '../../../tools/browser/new_tab/tool.json';
import w_32 from '../../../tools/browser/new_tab/workflow.json';
import k_32 from '../../../tools/browser/new_tab/knowledge.json';
import e_32 from '../../../tools/browser/new_tab/examples.json';
import s_32 from '../../../tools/browser/new_tab/tests.json';
import t_33 from '../../../tools/browser/bookmarks/tool.json';
import w_33 from '../../../tools/browser/bookmarks/workflow.json';
import k_33 from '../../../tools/browser/bookmarks/knowledge.json';
import e_33 from '../../../tools/browser/bookmarks/examples.json';
import s_33 from '../../../tools/browser/bookmarks/tests.json';
import t_34 from '../../../tools/browser/downloads/tool.json';
import w_34 from '../../../tools/browser/downloads/workflow.json';
import k_34 from '../../../tools/browser/downloads/knowledge.json';
import e_34 from '../../../tools/browser/downloads/examples.json';
import s_34 from '../../../tools/browser/downloads/tests.json';
import t_35 from '../../../tools/browser/history/tool.json';
import w_35 from '../../../tools/browser/history/workflow.json';
import k_35 from '../../../tools/browser/history/knowledge.json';
import e_35 from '../../../tools/browser/history/examples.json';
import s_35 from '../../../tools/browser/history/tests.json';
import t_36 from '../../../tools/browser/reload/tool.json';
import w_36 from '../../../tools/browser/reload/workflow.json';
import k_36 from '../../../tools/browser/reload/knowledge.json';
import e_36 from '../../../tools/browser/reload/examples.json';
import s_36 from '../../../tools/browser/reload/tests.json';
import t_37 from '../../../tools/browser/close_tabs/tool.json';
import w_37 from '../../../tools/browser/close_tabs/workflow.json';
import k_37 from '../../../tools/browser/close_tabs/knowledge.json';
import e_37 from '../../../tools/browser/close_tabs/examples.json';
import s_37 from '../../../tools/browser/close_tabs/tests.json';
import t_38 from '../../../tools/git/clone/tool.json';
import w_38 from '../../../tools/git/clone/workflow.json';
import k_38 from '../../../tools/git/clone/knowledge.json';
import e_38 from '../../../tools/git/clone/examples.json';
import s_38 from '../../../tools/git/clone/tests.json';
import t_39 from '../../../tools/git/commit/tool.json';
import w_39 from '../../../tools/git/commit/workflow.json';
import k_39 from '../../../tools/git/commit/knowledge.json';
import e_39 from '../../../tools/git/commit/examples.json';
import s_39 from '../../../tools/git/commit/tests.json';
import t_40 from '../../../tools/git/push/tool.json';
import w_40 from '../../../tools/git/push/workflow.json';
import k_40 from '../../../tools/git/push/knowledge.json';
import e_40 from '../../../tools/git/push/examples.json';
import s_40 from '../../../tools/git/push/tests.json';
import t_41 from '../../../tools/git/pull/tool.json';
import w_41 from '../../../tools/git/pull/workflow.json';
import k_41 from '../../../tools/git/pull/knowledge.json';
import e_41 from '../../../tools/git/pull/examples.json';
import s_41 from '../../../tools/git/pull/tests.json';
import t_42 from '../../../tools/git/checkout/tool.json';
import w_42 from '../../../tools/git/checkout/workflow.json';
import k_42 from '../../../tools/git/checkout/knowledge.json';
import e_42 from '../../../tools/git/checkout/examples.json';
import s_42 from '../../../tools/git/checkout/tests.json';
import t_43 from '../../../tools/git/merge/tool.json';
import w_43 from '../../../tools/git/merge/workflow.json';
import k_43 from '../../../tools/git/merge/knowledge.json';
import e_43 from '../../../tools/git/merge/examples.json';
import s_43 from '../../../tools/git/merge/tests.json';
import t_44 from '../../../tools/git/stash/tool.json';
import w_44 from '../../../tools/git/stash/workflow.json';
import k_44 from '../../../tools/git/stash/knowledge.json';
import e_44 from '../../../tools/git/stash/examples.json';
import s_44 from '../../../tools/git/stash/tests.json';
import t_45 from '../../../tools/git/branch/tool.json';
import w_45 from '../../../tools/git/branch/workflow.json';
import k_45 from '../../../tools/git/branch/knowledge.json';
import e_45 from '../../../tools/git/branch/examples.json';
import s_45 from '../../../tools/git/branch/tests.json';
import t_46 from '../../../tools/git/log/tool.json';
import w_46 from '../../../tools/git/log/workflow.json';
import k_46 from '../../../tools/git/log/knowledge.json';
import e_46 from '../../../tools/git/log/examples.json';
import s_46 from '../../../tools/git/log/tests.json';
import t_47 from '../../../tools/git/diff/tool.json';
import w_47 from '../../../tools/git/diff/workflow.json';
import k_47 from '../../../tools/git/diff/knowledge.json';
import e_47 from '../../../tools/git/diff/examples.json';
import s_47 from '../../../tools/git/diff/tests.json';
import t_48 from '../../../tools/docker/ps/tool.json';
import w_48 from '../../../tools/docker/ps/workflow.json';
import k_48 from '../../../tools/docker/ps/knowledge.json';
import e_48 from '../../../tools/docker/ps/examples.json';
import s_48 from '../../../tools/docker/ps/tests.json';
import t_49 from '../../../tools/docker/images/tool.json';
import w_49 from '../../../tools/docker/images/workflow.json';
import k_49 from '../../../tools/docker/images/knowledge.json';
import e_49 from '../../../tools/docker/images/examples.json';
import s_49 from '../../../tools/docker/images/tests.json';
import t_50 from '../../../tools/docker/logs/tool.json';
import w_50 from '../../../tools/docker/logs/workflow.json';
import k_50 from '../../../tools/docker/logs/knowledge.json';
import e_50 from '../../../tools/docker/logs/examples.json';
import s_50 from '../../../tools/docker/logs/tests.json';
import t_51 from '../../../tools/docker/exec/tool.json';
import w_51 from '../../../tools/docker/exec/workflow.json';
import k_51 from '../../../tools/docker/exec/knowledge.json';
import e_51 from '../../../tools/docker/exec/examples.json';
import s_51 from '../../../tools/docker/exec/tests.json';
import t_52 from '../../../tools/docker/compose_up/tool.json';
import w_52 from '../../../tools/docker/compose_up/workflow.json';
import k_52 from '../../../tools/docker/compose_up/knowledge.json';
import e_52 from '../../../tools/docker/compose_up/examples.json';
import s_52 from '../../../tools/docker/compose_up/tests.json';
import t_53 from '../../../tools/docker/compose_down/tool.json';
import w_53 from '../../../tools/docker/compose_down/workflow.json';
import k_53 from '../../../tools/docker/compose_down/knowledge.json';
import e_53 from '../../../tools/docker/compose_down/examples.json';
import s_53 from '../../../tools/docker/compose_down/tests.json';
import t_54 from '../../../tools/docker/stop/tool.json';
import w_54 from '../../../tools/docker/stop/workflow.json';
import k_54 from '../../../tools/docker/stop/knowledge.json';
import e_54 from '../../../tools/docker/stop/examples.json';
import s_54 from '../../../tools/docker/stop/tests.json';
import t_55 from '../../../tools/docker/restart/tool.json';
import w_55 from '../../../tools/docker/restart/workflow.json';
import k_55 from '../../../tools/docker/restart/knowledge.json';
import e_55 from '../../../tools/docker/restart/examples.json';
import s_55 from '../../../tools/docker/restart/tests.json';
import t_56 from '../../../tools/node/npm_install/tool.json';
import w_56 from '../../../tools/node/npm_install/workflow.json';
import k_56 from '../../../tools/node/npm_install/knowledge.json';
import e_56 from '../../../tools/node/npm_install/examples.json';
import s_56 from '../../../tools/node/npm_install/tests.json';
import t_57 from '../../../tools/node/npm_run/tool.json';
import w_57 from '../../../tools/node/npm_run/workflow.json';
import k_57 from '../../../tools/node/npm_run/knowledge.json';
import e_57 from '../../../tools/node/npm_run/examples.json';
import s_57 from '../../../tools/node/npm_run/tests.json';
import t_58 from '../../../tools/node/pnpm/tool.json';
import w_58 from '../../../tools/node/pnpm/workflow.json';
import k_58 from '../../../tools/node/pnpm/knowledge.json';
import e_58 from '../../../tools/node/pnpm/examples.json';
import s_58 from '../../../tools/node/pnpm/tests.json';
import t_59 from '../../../tools/node/bun/tool.json';
import w_59 from '../../../tools/node/bun/workflow.json';
import k_59 from '../../../tools/node/bun/knowledge.json';
import e_59 from '../../../tools/node/bun/examples.json';
import s_59 from '../../../tools/node/bun/tests.json';
import t_60 from '../../../tools/node/yarn/tool.json';
import w_60 from '../../../tools/node/yarn/workflow.json';
import k_60 from '../../../tools/node/yarn/knowledge.json';
import e_60 from '../../../tools/node/yarn/examples.json';
import s_60 from '../../../tools/node/yarn/tests.json';
import t_61 from '../../../tools/python/create_venv/tool.json';
import w_61 from '../../../tools/python/create_venv/workflow.json';
import k_61 from '../../../tools/python/create_venv/knowledge.json';
import e_61 from '../../../tools/python/create_venv/examples.json';
import s_61 from '../../../tools/python/create_venv/tests.json';
import t_62 from '../../../tools/python/pip_install/tool.json';
import w_62 from '../../../tools/python/pip_install/workflow.json';
import k_62 from '../../../tools/python/pip_install/knowledge.json';
import e_62 from '../../../tools/python/pip_install/examples.json';
import s_62 from '../../../tools/python/pip_install/tests.json';
import t_63 from '../../../tools/python/run_script/tool.json';
import w_63 from '../../../tools/python/run_script/workflow.json';
import k_63 from '../../../tools/python/run_script/knowledge.json';
import e_63 from '../../../tools/python/run_script/examples.json';
import s_63 from '../../../tools/python/run_script/tests.json';
import t_64 from '../../../tools/python/notebook/tool.json';
import w_64 from '../../../tools/python/notebook/workflow.json';
import k_64 from '../../../tools/python/notebook/knowledge.json';
import e_64 from '../../../tools/python/notebook/examples.json';
import s_64 from '../../../tools/python/notebook/tests.json';
import t_65 from '../../../tools/network/wifi.scan/tool.json';
import w_65 from '../../../tools/network/wifi.scan/workflow.json';
import k_65 from '../../../tools/network/wifi.scan/knowledge.json';
import e_65 from '../../../tools/network/wifi.scan/examples.json';
import s_65 from '../../../tools/network/wifi.scan/tests.json';
import t_66 from '../../../tools/network/wifi.connect/tool.json';
import w_66 from '../../../tools/network/wifi.connect/workflow.json';
import k_66 from '../../../tools/network/wifi.connect/knowledge.json';
import e_66 from '../../../tools/network/wifi.connect/examples.json';
import s_66 from '../../../tools/network/wifi.connect/tests.json';
import t_67 from '../../../tools/network/wifi.on/tool.json';
import w_67 from '../../../tools/network/wifi.on/workflow.json';
import k_67 from '../../../tools/network/wifi.on/knowledge.json';
import e_67 from '../../../tools/network/wifi.on/examples.json';
import s_67 from '../../../tools/network/wifi.on/tests.json';
import t_68 from '../../../tools/network/wifi.off/tool.json';
import w_68 from '../../../tools/network/wifi.off/workflow.json';
import k_68 from '../../../tools/network/wifi.off/knowledge.json';
import e_68 from '../../../tools/network/wifi.off/examples.json';
import s_68 from '../../../tools/network/wifi.off/tests.json';
import t_69 from '../../../tools/network/bluetooth.list/tool.json';
import w_69 from '../../../tools/network/bluetooth.list/workflow.json';
import k_69 from '../../../tools/network/bluetooth.list/knowledge.json';
import e_69 from '../../../tools/network/bluetooth.list/examples.json';
import s_69 from '../../../tools/network/bluetooth.list/tests.json';
import t_70 from '../../../tools/network/bluetooth.on/tool.json';
import w_70 from '../../../tools/network/bluetooth.on/workflow.json';
import k_70 from '../../../tools/network/bluetooth.on/knowledge.json';
import e_70 from '../../../tools/network/bluetooth.on/examples.json';
import s_70 from '../../../tools/network/bluetooth.on/tests.json';
import t_71 from '../../../tools/network/bluetooth.off/tool.json';
import w_71 from '../../../tools/network/bluetooth.off/workflow.json';
import k_71 from '../../../tools/network/bluetooth.off/knowledge.json';
import e_71 from '../../../tools/network/bluetooth.off/examples.json';
import s_71 from '../../../tools/network/bluetooth.off/tests.json';
import t_72 from '../../../tools/network/bluetooth.connect/tool.json';
import w_72 from '../../../tools/network/bluetooth.connect/workflow.json';
import k_72 from '../../../tools/network/bluetooth.connect/knowledge.json';
import e_72 from '../../../tools/network/bluetooth.connect/examples.json';
import s_72 from '../../../tools/network/bluetooth.connect/tests.json';
import t_73 from '../../../tools/network/ping/tool.json';
import w_73 from '../../../tools/network/ping/workflow.json';
import k_73 from '../../../tools/network/ping/knowledge.json';
import e_73 from '../../../tools/network/ping/examples.json';
import s_73 from '../../../tools/network/ping/tests.json';
import t_74 from '../../../tools/network/traceroute/tool.json';
import w_74 from '../../../tools/network/traceroute/workflow.json';
import k_74 from '../../../tools/network/traceroute/knowledge.json';
import e_74 from '../../../tools/network/traceroute/examples.json';
import s_74 from '../../../tools/network/traceroute/tests.json';
import t_75 from '../../../tools/network/ports/tool.json';
import w_75 from '../../../tools/network/ports/workflow.json';
import k_75 from '../../../tools/network/ports/knowledge.json';
import e_75 from '../../../tools/network/ports/examples.json';
import s_75 from '../../../tools/network/ports/tests.json';
import t_76 from '../../../tools/network/interfaces/tool.json';
import w_76 from '../../../tools/network/interfaces/workflow.json';
import k_76 from '../../../tools/network/interfaces/knowledge.json';
import e_76 from '../../../tools/network/interfaces/examples.json';
import s_76 from '../../../tools/network/interfaces/tests.json';
import t_77 from '../../../tools/network/dns/tool.json';
import w_77 from '../../../tools/network/dns/workflow.json';
import k_77 from '../../../tools/network/dns/knowledge.json';
import e_77 from '../../../tools/network/dns/examples.json';
import s_77 from '../../../tools/network/dns/tests.json';
import t_78 from '../../../tools/network/ip/tool.json';
import w_78 from '../../../tools/network/ip/workflow.json';
import k_78 from '../../../tools/network/ip/knowledge.json';
import e_78 from '../../../tools/network/ip/examples.json';
import s_78 from '../../../tools/network/ip/tests.json';
import t_79 from '../../../tools/system/info/tool.json';
import w_79 from '../../../tools/system/info/workflow.json';
import k_79 from '../../../tools/system/info/knowledge.json';
import e_79 from '../../../tools/system/info/examples.json';
import s_79 from '../../../tools/system/info/tests.json';
import t_80 from '../../../tools/system/battery/tool.json';
import w_80 from '../../../tools/system/battery/workflow.json';
import k_80 from '../../../tools/system/battery/knowledge.json';
import e_80 from '../../../tools/system/battery/examples.json';
import s_80 from '../../../tools/system/battery/tests.json';
import t_81 from '../../../tools/system/cpu/tool.json';
import w_81 from '../../../tools/system/cpu/workflow.json';
import k_81 from '../../../tools/system/cpu/knowledge.json';
import e_81 from '../../../tools/system/cpu/examples.json';
import s_81 from '../../../tools/system/cpu/tests.json';
import t_82 from '../../../tools/system/gpu/tool.json';
import w_82 from '../../../tools/system/gpu/workflow.json';
import k_82 from '../../../tools/system/gpu/knowledge.json';
import e_82 from '../../../tools/system/gpu/examples.json';
import s_82 from '../../../tools/system/gpu/tests.json';
import t_83 from '../../../tools/system/ram/tool.json';
import w_83 from '../../../tools/system/ram/workflow.json';
import k_83 from '../../../tools/system/ram/knowledge.json';
import e_83 from '../../../tools/system/ram/examples.json';
import s_83 from '../../../tools/system/ram/tests.json';
import t_84 from '../../../tools/system/storage/tool.json';
import w_84 from '../../../tools/system/storage/workflow.json';
import k_84 from '../../../tools/system/storage/knowledge.json';
import e_84 from '../../../tools/system/storage/examples.json';
import s_84 from '../../../tools/system/storage/tests.json';
import t_85 from '../../../tools/system/processes/tool.json';
import w_85 from '../../../tools/system/processes/workflow.json';
import k_85 from '../../../tools/system/processes/knowledge.json';
import e_85 from '../../../tools/system/processes/examples.json';
import s_85 from '../../../tools/system/processes/tests.json';
import t_86 from '../../../tools/system/temperature/tool.json';
import w_86 from '../../../tools/system/temperature/workflow.json';
import k_86 from '../../../tools/system/temperature/knowledge.json';
import e_86 from '../../../tools/system/temperature/examples.json';
import s_86 from '../../../tools/system/temperature/tests.json';
import t_87 from '../../../tools/system/uptime/tool.json';
import w_87 from '../../../tools/system/uptime/workflow.json';
import k_87 from '../../../tools/system/uptime/knowledge.json';
import e_87 from '../../../tools/system/uptime/examples.json';
import s_87 from '../../../tools/system/uptime/tests.json';
import t_88 from '../../../tools/system/kill_process/tool.json';
import w_88 from '../../../tools/system/kill_process/workflow.json';
import k_88 from '../../../tools/system/kill_process/knowledge.json';
import e_88 from '../../../tools/system/kill_process/examples.json';
import s_88 from '../../../tools/system/kill_process/tests.json';
import t_89 from '../../../tools/shell/execute/tool.json';
import w_89 from '../../../tools/shell/execute/workflow.json';
import k_89 from '../../../tools/shell/execute/knowledge.json';
import e_89 from '../../../tools/shell/execute/examples.json';
import s_89 from '../../../tools/shell/execute/tests.json';
import t_90 from '../../../tools/developer/vscode/tool.json';
import w_90 from '../../../tools/developer/vscode/workflow.json';
import k_90 from '../../../tools/developer/vscode/knowledge.json';
import e_90 from '../../../tools/developer/vscode/examples.json';
import s_90 from '../../../tools/developer/vscode/tests.json';
import t_91 from '../../../tools/developer/cursor/tool.json';
import w_91 from '../../../tools/developer/cursor/workflow.json';
import k_91 from '../../../tools/developer/cursor/knowledge.json';
import e_91 from '../../../tools/developer/cursor/examples.json';
import s_91 from '../../../tools/developer/cursor/tests.json';
import t_92 from '../../../tools/developer/xcode/tool.json';
import w_92 from '../../../tools/developer/xcode/workflow.json';
import k_92 from '../../../tools/developer/xcode/knowledge.json';
import e_92 from '../../../tools/developer/xcode/examples.json';
import s_92 from '../../../tools/developer/xcode/tests.json';
import t_93 from '../../../tools/developer/android_studio/tool.json';
import w_93 from '../../../tools/developer/android_studio/workflow.json';
import k_93 from '../../../tools/developer/android_studio/knowledge.json';
import e_93 from '../../../tools/developer/android_studio/examples.json';
import s_93 from '../../../tools/developer/android_studio/tests.json';
import t_94 from '../../../tools/developer/terminal/tool.json';
import w_94 from '../../../tools/developer/terminal/workflow.json';
import k_94 from '../../../tools/developer/terminal/knowledge.json';
import e_94 from '../../../tools/developer/terminal/examples.json';
import s_94 from '../../../tools/developer/terminal/tests.json';
import t_95 from '../../../tools/developer/ssh/tool.json';
import w_95 from '../../../tools/developer/ssh/workflow.json';
import k_95 from '../../../tools/developer/ssh/knowledge.json';
import e_95 from '../../../tools/developer/ssh/examples.json';
import s_95 from '../../../tools/developer/ssh/tests.json';
import t_96 from '../../../tools/developer/github/tool.json';
import w_96 from '../../../tools/developer/github/workflow.json';
import k_96 from '../../../tools/developer/github/knowledge.json';
import e_96 from '../../../tools/developer/github/examples.json';
import s_96 from '../../../tools/developer/github/tests.json';

export const BUNDLED_TOOLS: RawToolBundle[] = [
  {
    tool: t_0 as any, workflow: w_0 as any,
    knowledge: k_0 as any, examples: e_0 as any,
    tests: s_0 as any, folderPath: 'tools/filesystem/list'
  },
  {
    tool: t_1 as any, workflow: w_1 as any,
    knowledge: k_1 as any, examples: e_1 as any,
    tests: s_1 as any, folderPath: 'tools/filesystem/navigate'
  },
  {
    tool: t_2 as any, workflow: w_2 as any,
    knowledge: k_2 as any, examples: e_2 as any,
    tests: s_2 as any, folderPath: 'tools/filesystem/read'
  },
  {
    tool: t_3 as any, workflow: w_3 as any,
    knowledge: k_3 as any, examples: e_3 as any,
    tests: s_3 as any, folderPath: 'tools/filesystem/search'
  },
  {
    tool: t_4 as any, workflow: w_4 as any,
    knowledge: k_4 as any, examples: e_4 as any,
    tests: s_4 as any, folderPath: 'tools/filesystem/copy'
  },
  {
    tool: t_5 as any, workflow: w_5 as any,
    knowledge: k_5 as any, examples: e_5 as any,
    tests: s_5 as any, folderPath: 'tools/filesystem/locate_files'
  },
  {
    tool: t_6 as any, workflow: w_6 as any,
    knowledge: k_6 as any, examples: e_6 as any,
    tests: s_6 as any, folderPath: 'tools/filesystem/locate_folders'
  },
  {
    tool: t_7 as any, workflow: w_7 as any,
    knowledge: k_7 as any, examples: e_7 as any,
    tests: s_7 as any, folderPath: 'tools/filesystem/grep'
  },
  {
    tool: t_8 as any, workflow: w_8 as any,
    knowledge: k_8 as any, examples: e_8 as any,
    tests: s_8 as any, folderPath: 'tools/filesystem/move'
  },
  {
    tool: t_9 as any, workflow: w_9 as any,
    knowledge: k_9 as any, examples: e_9 as any,
    tests: s_9 as any, folderPath: 'tools/filesystem/rename'
  },
  {
    tool: t_10 as any, workflow: w_10 as any,
    knowledge: k_10 as any, examples: e_10 as any,
    tests: s_10 as any, folderPath: 'tools/filesystem/compress'
  },
  {
    tool: t_11 as any, workflow: w_11 as any,
    knowledge: k_11 as any, examples: e_11 as any,
    tests: s_11 as any, folderPath: 'tools/filesystem/extract'
  },
  {
    tool: t_12 as any, workflow: w_12 as any,
    knowledge: k_12 as any, examples: e_12 as any,
    tests: s_12 as any, folderPath: 'tools/filesystem/duplicate'
  },
  {
    tool: t_13 as any, workflow: w_13 as any,
    knowledge: k_13 as any, examples: e_13 as any,
    tests: s_13 as any, folderPath: 'tools/filesystem/delete'
  },
  {
    tool: t_14 as any, workflow: w_14 as any,
    knowledge: k_14 as any, examples: e_14 as any,
    tests: s_14 as any, folderPath: 'tools/filesystem/trash'
  },
  {
    tool: t_15 as any, workflow: w_15 as any,
    knowledge: k_15 as any, examples: e_15 as any,
    tests: s_15 as any, folderPath: 'tools/filesystem/restore'
  },
  {
    tool: t_16 as any, workflow: w_16 as any,
    knowledge: k_16 as any, examples: e_16 as any,
    tests: s_16 as any, folderPath: 'tools/filesystem/permissions'
  },
  {
    tool: t_17 as any, workflow: w_17 as any,
    knowledge: k_17 as any, examples: e_17 as any,
    tests: s_17 as any, folderPath: 'tools/filesystem/disk_usage'
  },
  {
    tool: t_18 as any, workflow: w_18 as any,
    knowledge: k_18 as any, examples: e_18 as any,
    tests: s_18 as any, folderPath: 'tools/filesystem/recent_files'
  },
  {
    tool: t_19 as any, workflow: w_19 as any,
    knowledge: k_19 as any, examples: e_19 as any,
    tests: s_19 as any, folderPath: 'tools/filesystem/mkdir'
  },
  {
    tool: t_20 as any, workflow: w_20 as any,
    knowledge: k_20 as any, examples: e_20 as any,
    tests: s_20 as any, folderPath: 'tools/filesystem/create'
  },
  {
    tool: t_21 as any, workflow: w_21 as any,
    knowledge: k_21 as any, examples: e_21 as any,
    tests: s_21 as any, folderPath: 'tools/application/open'
  },
  {
    tool: t_22 as any, workflow: w_22 as any,
    knowledge: k_22 as any, examples: e_22 as any,
    tests: s_22 as any, folderPath: 'tools/application/close'
  },
  {
    tool: t_23 as any, workflow: w_23 as any,
    knowledge: k_23 as any, examples: e_23 as any,
    tests: s_23 as any, folderPath: 'tools/application/force_quit'
  },
  {
    tool: t_24 as any, workflow: w_24 as any,
    knowledge: k_24 as any, examples: e_24 as any,
    tests: s_24 as any, folderPath: 'tools/application/focus'
  },
  {
    tool: t_25 as any, workflow: w_25 as any,
    knowledge: k_25 as any, examples: e_25 as any,
    tests: s_25 as any, folderPath: 'tools/application/minimize'
  },
  {
    tool: t_26 as any, workflow: w_26 as any,
    knowledge: k_26 as any, examples: e_26 as any,
    tests: s_26 as any, folderPath: 'tools/application/maximize'
  },
  {
    tool: t_27 as any, workflow: w_27 as any,
    knowledge: k_27 as any, examples: e_27 as any,
    tests: s_27 as any, folderPath: 'tools/application/list_running'
  },
  {
    tool: t_28 as any, workflow: w_28 as any,
    knowledge: k_28 as any, examples: e_28 as any,
    tests: s_28 as any, folderPath: 'tools/application/install'
  },
  {
    tool: t_29 as any, workflow: w_29 as any,
    knowledge: k_29 as any, examples: e_29 as any,
    tests: s_29 as any, folderPath: 'tools/application/uninstall'
  },
  {
    tool: t_30 as any, workflow: w_30 as any,
    knowledge: k_30 as any, examples: e_30 as any,
    tests: s_30 as any, folderPath: 'tools/browser/navigate'
  },
  {
    tool: t_31 as any, workflow: w_31 as any,
    knowledge: k_31 as any, examples: e_31 as any,
    tests: s_31 as any, folderPath: 'tools/browser/search'
  },
  {
    tool: t_32 as any, workflow: w_32 as any,
    knowledge: k_32 as any, examples: e_32 as any,
    tests: s_32 as any, folderPath: 'tools/browser/new_tab'
  },
  {
    tool: t_33 as any, workflow: w_33 as any,
    knowledge: k_33 as any, examples: e_33 as any,
    tests: s_33 as any, folderPath: 'tools/browser/bookmarks'
  },
  {
    tool: t_34 as any, workflow: w_34 as any,
    knowledge: k_34 as any, examples: e_34 as any,
    tests: s_34 as any, folderPath: 'tools/browser/downloads'
  },
  {
    tool: t_35 as any, workflow: w_35 as any,
    knowledge: k_35 as any, examples: e_35 as any,
    tests: s_35 as any, folderPath: 'tools/browser/history'
  },
  {
    tool: t_36 as any, workflow: w_36 as any,
    knowledge: k_36 as any, examples: e_36 as any,
    tests: s_36 as any, folderPath: 'tools/browser/reload'
  },
  {
    tool: t_37 as any, workflow: w_37 as any,
    knowledge: k_37 as any, examples: e_37 as any,
    tests: s_37 as any, folderPath: 'tools/browser/close_tabs'
  },
  {
    tool: t_38 as any, workflow: w_38 as any,
    knowledge: k_38 as any, examples: e_38 as any,
    tests: s_38 as any, folderPath: 'tools/git/clone'
  },
  {
    tool: t_39 as any, workflow: w_39 as any,
    knowledge: k_39 as any, examples: e_39 as any,
    tests: s_39 as any, folderPath: 'tools/git/commit'
  },
  {
    tool: t_40 as any, workflow: w_40 as any,
    knowledge: k_40 as any, examples: e_40 as any,
    tests: s_40 as any, folderPath: 'tools/git/push'
  },
  {
    tool: t_41 as any, workflow: w_41 as any,
    knowledge: k_41 as any, examples: e_41 as any,
    tests: s_41 as any, folderPath: 'tools/git/pull'
  },
  {
    tool: t_42 as any, workflow: w_42 as any,
    knowledge: k_42 as any, examples: e_42 as any,
    tests: s_42 as any, folderPath: 'tools/git/checkout'
  },
  {
    tool: t_43 as any, workflow: w_43 as any,
    knowledge: k_43 as any, examples: e_43 as any,
    tests: s_43 as any, folderPath: 'tools/git/merge'
  },
  {
    tool: t_44 as any, workflow: w_44 as any,
    knowledge: k_44 as any, examples: e_44 as any,
    tests: s_44 as any, folderPath: 'tools/git/stash'
  },
  {
    tool: t_45 as any, workflow: w_45 as any,
    knowledge: k_45 as any, examples: e_45 as any,
    tests: s_45 as any, folderPath: 'tools/git/branch'
  },
  {
    tool: t_46 as any, workflow: w_46 as any,
    knowledge: k_46 as any, examples: e_46 as any,
    tests: s_46 as any, folderPath: 'tools/git/log'
  },
  {
    tool: t_47 as any, workflow: w_47 as any,
    knowledge: k_47 as any, examples: e_47 as any,
    tests: s_47 as any, folderPath: 'tools/git/diff'
  },
  {
    tool: t_48 as any, workflow: w_48 as any,
    knowledge: k_48 as any, examples: e_48 as any,
    tests: s_48 as any, folderPath: 'tools/docker/ps'
  },
  {
    tool: t_49 as any, workflow: w_49 as any,
    knowledge: k_49 as any, examples: e_49 as any,
    tests: s_49 as any, folderPath: 'tools/docker/images'
  },
  {
    tool: t_50 as any, workflow: w_50 as any,
    knowledge: k_50 as any, examples: e_50 as any,
    tests: s_50 as any, folderPath: 'tools/docker/logs'
  },
  {
    tool: t_51 as any, workflow: w_51 as any,
    knowledge: k_51 as any, examples: e_51 as any,
    tests: s_51 as any, folderPath: 'tools/docker/exec'
  },
  {
    tool: t_52 as any, workflow: w_52 as any,
    knowledge: k_52 as any, examples: e_52 as any,
    tests: s_52 as any, folderPath: 'tools/docker/compose_up'
  },
  {
    tool: t_53 as any, workflow: w_53 as any,
    knowledge: k_53 as any, examples: e_53 as any,
    tests: s_53 as any, folderPath: 'tools/docker/compose_down'
  },
  {
    tool: t_54 as any, workflow: w_54 as any,
    knowledge: k_54 as any, examples: e_54 as any,
    tests: s_54 as any, folderPath: 'tools/docker/stop'
  },
  {
    tool: t_55 as any, workflow: w_55 as any,
    knowledge: k_55 as any, examples: e_55 as any,
    tests: s_55 as any, folderPath: 'tools/docker/restart'
  },
  {
    tool: t_56 as any, workflow: w_56 as any,
    knowledge: k_56 as any, examples: e_56 as any,
    tests: s_56 as any, folderPath: 'tools/node/npm_install'
  },
  {
    tool: t_57 as any, workflow: w_57 as any,
    knowledge: k_57 as any, examples: e_57 as any,
    tests: s_57 as any, folderPath: 'tools/node/npm_run'
  },
  {
    tool: t_58 as any, workflow: w_58 as any,
    knowledge: k_58 as any, examples: e_58 as any,
    tests: s_58 as any, folderPath: 'tools/node/pnpm'
  },
  {
    tool: t_59 as any, workflow: w_59 as any,
    knowledge: k_59 as any, examples: e_59 as any,
    tests: s_59 as any, folderPath: 'tools/node/bun'
  },
  {
    tool: t_60 as any, workflow: w_60 as any,
    knowledge: k_60 as any, examples: e_60 as any,
    tests: s_60 as any, folderPath: 'tools/node/yarn'
  },
  {
    tool: t_61 as any, workflow: w_61 as any,
    knowledge: k_61 as any, examples: e_61 as any,
    tests: s_61 as any, folderPath: 'tools/python/create_venv'
  },
  {
    tool: t_62 as any, workflow: w_62 as any,
    knowledge: k_62 as any, examples: e_62 as any,
    tests: s_62 as any, folderPath: 'tools/python/pip_install'
  },
  {
    tool: t_63 as any, workflow: w_63 as any,
    knowledge: k_63 as any, examples: e_63 as any,
    tests: s_63 as any, folderPath: 'tools/python/run_script'
  },
  {
    tool: t_64 as any, workflow: w_64 as any,
    knowledge: k_64 as any, examples: e_64 as any,
    tests: s_64 as any, folderPath: 'tools/python/notebook'
  },
  {
    tool: t_65 as any, workflow: w_65 as any,
    knowledge: k_65 as any, examples: e_65 as any,
    tests: s_65 as any, folderPath: 'tools/network/wifi.scan'
  },
  {
    tool: t_66 as any, workflow: w_66 as any,
    knowledge: k_66 as any, examples: e_66 as any,
    tests: s_66 as any, folderPath: 'tools/network/wifi.connect'
  },
  {
    tool: t_67 as any, workflow: w_67 as any,
    knowledge: k_67 as any, examples: e_67 as any,
    tests: s_67 as any, folderPath: 'tools/network/wifi.on'
  },
  {
    tool: t_68 as any, workflow: w_68 as any,
    knowledge: k_68 as any, examples: e_68 as any,
    tests: s_68 as any, folderPath: 'tools/network/wifi.off'
  },
  {
    tool: t_69 as any, workflow: w_69 as any,
    knowledge: k_69 as any, examples: e_69 as any,
    tests: s_69 as any, folderPath: 'tools/network/bluetooth.list'
  },
  {
    tool: t_70 as any, workflow: w_70 as any,
    knowledge: k_70 as any, examples: e_70 as any,
    tests: s_70 as any, folderPath: 'tools/network/bluetooth.on'
  },
  {
    tool: t_71 as any, workflow: w_71 as any,
    knowledge: k_71 as any, examples: e_71 as any,
    tests: s_71 as any, folderPath: 'tools/network/bluetooth.off'
  },
  {
    tool: t_72 as any, workflow: w_72 as any,
    knowledge: k_72 as any, examples: e_72 as any,
    tests: s_72 as any, folderPath: 'tools/network/bluetooth.connect'
  },
  {
    tool: t_73 as any, workflow: w_73 as any,
    knowledge: k_73 as any, examples: e_73 as any,
    tests: s_73 as any, folderPath: 'tools/network/ping'
  },
  {
    tool: t_74 as any, workflow: w_74 as any,
    knowledge: k_74 as any, examples: e_74 as any,
    tests: s_74 as any, folderPath: 'tools/network/traceroute'
  },
  {
    tool: t_75 as any, workflow: w_75 as any,
    knowledge: k_75 as any, examples: e_75 as any,
    tests: s_75 as any, folderPath: 'tools/network/ports'
  },
  {
    tool: t_76 as any, workflow: w_76 as any,
    knowledge: k_76 as any, examples: e_76 as any,
    tests: s_76 as any, folderPath: 'tools/network/interfaces'
  },
  {
    tool: t_77 as any, workflow: w_77 as any,
    knowledge: k_77 as any, examples: e_77 as any,
    tests: s_77 as any, folderPath: 'tools/network/dns'
  },
  {
    tool: t_78 as any, workflow: w_78 as any,
    knowledge: k_78 as any, examples: e_78 as any,
    tests: s_78 as any, folderPath: 'tools/network/ip'
  },
  {
    tool: t_79 as any, workflow: w_79 as any,
    knowledge: k_79 as any, examples: e_79 as any,
    tests: s_79 as any, folderPath: 'tools/system/info'
  },
  {
    tool: t_80 as any, workflow: w_80 as any,
    knowledge: k_80 as any, examples: e_80 as any,
    tests: s_80 as any, folderPath: 'tools/system/battery'
  },
  {
    tool: t_81 as any, workflow: w_81 as any,
    knowledge: k_81 as any, examples: e_81 as any,
    tests: s_81 as any, folderPath: 'tools/system/cpu'
  },
  {
    tool: t_82 as any, workflow: w_82 as any,
    knowledge: k_82 as any, examples: e_82 as any,
    tests: s_82 as any, folderPath: 'tools/system/gpu'
  },
  {
    tool: t_83 as any, workflow: w_83 as any,
    knowledge: k_83 as any, examples: e_83 as any,
    tests: s_83 as any, folderPath: 'tools/system/ram'
  },
  {
    tool: t_84 as any, workflow: w_84 as any,
    knowledge: k_84 as any, examples: e_84 as any,
    tests: s_84 as any, folderPath: 'tools/system/storage'
  },
  {
    tool: t_85 as any, workflow: w_85 as any,
    knowledge: k_85 as any, examples: e_85 as any,
    tests: s_85 as any, folderPath: 'tools/system/processes'
  },
  {
    tool: t_86 as any, workflow: w_86 as any,
    knowledge: k_86 as any, examples: e_86 as any,
    tests: s_86 as any, folderPath: 'tools/system/temperature'
  },
  {
    tool: t_87 as any, workflow: w_87 as any,
    knowledge: k_87 as any, examples: e_87 as any,
    tests: s_87 as any, folderPath: 'tools/system/uptime'
  },
  {
    tool: t_88 as any, workflow: w_88 as any,
    knowledge: k_88 as any, examples: e_88 as any,
    tests: s_88 as any, folderPath: 'tools/system/kill_process'
  },
  {
    tool: t_89 as any, workflow: w_89 as any,
    knowledge: k_89 as any, examples: e_89 as any,
    tests: s_89 as any, folderPath: 'tools/shell/execute'
  },
  {
    tool: t_90 as any, workflow: w_90 as any,
    knowledge: k_90 as any, examples: e_90 as any,
    tests: s_90 as any, folderPath: 'tools/developer/vscode'
  },
  {
    tool: t_91 as any, workflow: w_91 as any,
    knowledge: k_91 as any, examples: e_91 as any,
    tests: s_91 as any, folderPath: 'tools/developer/cursor'
  },
  {
    tool: t_92 as any, workflow: w_92 as any,
    knowledge: k_92 as any, examples: e_92 as any,
    tests: s_92 as any, folderPath: 'tools/developer/xcode'
  },
  {
    tool: t_93 as any, workflow: w_93 as any,
    knowledge: k_93 as any, examples: e_93 as any,
    tests: s_93 as any, folderPath: 'tools/developer/android_studio'
  },
  {
    tool: t_94 as any, workflow: w_94 as any,
    knowledge: k_94 as any, examples: e_94 as any,
    tests: s_94 as any, folderPath: 'tools/developer/terminal'
  },
  {
    tool: t_95 as any, workflow: w_95 as any,
    knowledge: k_95 as any, examples: e_95 as any,
    tests: s_95 as any, folderPath: 'tools/developer/ssh'
  },
  {
    tool: t_96 as any, workflow: w_96 as any,
    knowledge: k_96 as any, examples: e_96 as any,
    tests: s_96 as any, folderPath: 'tools/developer/github'
  },
];
